test: add tests that passes data through Plug.Parsers
supabase/plug_caisson pull request #16
Opened 2024-01-02 20:20 UTC by hauleth

This also adds tests for `identity` content encoding and for situation
when there is no content encoding header at all.

2024-01-03 15:22 UTC, Ziinc requested changes
adding testing and the private state management seem like separate concerns, should separate out to different PRs.
Also, missing testing for custom state setting.

2024-01-03 15:22 UTC, Ziinc commented on lib/plug_caisson.ex
> +              {:ok, binary(), new_state :: term()}
Should document how state can be used by custom algos, and how it can be utilized in downstream plugs in the pipeline.

2024-01-03 16:28 UTC, hauleth commented on lib/plug_caisson.ex
> +              {:ok, binary(), new_state :: term()}
I will move that to separate PR.

2024-01-04 07:48 UTC, Ziinc approved these changes
looks great. Can consolidate the repetitive tests in a follow up PR, this looks good for announcement now.

2024-01-04 07:48 UTC, Ziinc commented on lib/plug_caisson.ex
>            _ ->
small nit: this entire `fetch_decompressor/2` block should be refactored to a `with ... do...else` with the `content_encoding` case as the happy path and all other situations under `else`. The 3 level nesting affects readability quite a bit.

2024-01-04 07:49 UTC, merged